# Generated by Django 5.0.4 on 2024-05-23 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter first name', max_length=250)),
                ('surname', models.CharField(help_text='Enter last name', max_length=250)),
                ('about', models.CharField(help_text='Tell us about yourself', max_length=2000)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title for a new article', max_length=250)),
                ('text', models.CharField(help_text='Enter text for a new article', max_length=2500)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.user')),
            ],
        ),
    ]
