# Use the official Redis image as a base
FROM redis/redis-stack-server:latest

# Expose the default Redis port
EXPOSE 6379

# run de container with
# build docker container with
# docker build -t redis-server . (yes the . needs to be there)
# docker docker run --name my-redis-container -d redis-server
# to go into the terminal from the docker container use
#